import {
  ArrowDown,
  ArrowLeft,
  ArrowRightLeft,
  Banknote,
  Bell,
  BellRing,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Car,
  Calendar,
  CalendarClock,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  ClipboardList,
  Cloud,
  RefreshCw,
  Clock,
  Construction,
  Download,
  File,
  FileArchive,
  FileDown,
  FilePen,
  FilePenLine,
  FileSpreadsheet,
  FileText,
  Flag,
  Ghost,
  GitCommitHorizontal,
  Hammer,
  HardHat,
  Hash,
  History,
  IdCard,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  LifeBuoy,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Minus,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Receipt,
  Save,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  Sheet,
  Sigma,
  Sparkles,
  Star,
  Stethoscope,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

// Registro esplicito delle sole icone usate: evita di includere nel bundle
// l'intero set Lucide (~1700 icone). Aggiungere qui le nuove icone usate.
export const iconMap: Record<string, LucideIcon> = {
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right-left': ArrowRightLeft,
  'banknote': Banknote,
  'bell': Bell,
  'bell-ring': BellRing,
  'briefcase': Briefcase,
  'building': Building,
  'building-2': Building2,
  'calculator': Calculator,
  'car': Car,
  'calendar': Calendar,
  'calendar-clock': CalendarClock,
  'chart-column': ChartColumn,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-question-mark': CircleQuestionMark,
  'circle-x': CircleX,
  'clipboard-list': ClipboardList,
  'cloud': Cloud,
  'refresh-cw': RefreshCw,
  'clock': Clock,
  'construction': Construction,
  'download': Download,
  'file': File,
  'file-archive': FileArchive,
  'file-down': FileDown,
  'file-pen': FilePen,
  'file-pen-line': FilePenLine,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'flag': Flag,
  'ghost': Ghost,
  'git-commit-horizontal': GitCommitHorizontal,
  'hammer': Hammer,
  'hard-hat': HardHat,
  'hash': Hash,
  'history': History,
  'id-card': IdCard,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  'loader-circle': LoaderCircle,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'minus': Minus,
  'package': Package,
  'paperclip': Paperclip,
  'pause': Pause,
  'pencil': Pencil,
  'phone': Phone,
  'play': Play,
  'plus': Plus,
  'receipt': Receipt,
  'save': Save,
  'scale': Scale,
  'search': Search,
  'search-x': SearchX,
  'send': Send,
  'settings': Settings,
  'shield-check': ShieldCheck,
  'sheet': Sheet,
  'sigma': Sigma,
  'sparkles': Sparkles,
  'star': Star,
  'stethoscope': Stethoscope,
  'tag': Tag,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'truck': Truck,
  'upload': Upload,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'wallet': Wallet,
  'wrench': Wrench,
}
